# Generated by Django 4.1.4 on 2022-12-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст заметки')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
                ('category', models.CharField(blank=True, choices=[('link', 'Ссылка'), ('note', 'Заметка'), ('memo', 'Памятка'), ('todo', 'TODO')], max_length=4, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
