# Generated by Django 4.1.4 on 2022-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
    ]
